from typing import Dict, Any
from ....utils.fsFormat import formatarValor, formatarData, tipoOperacao, documentoProprio, modeloDoc, situacaoDoc, tipoFrete, tipoFatura

def builderNFM(dados: Dict[str, Any]) -> str:
    campos = [''] * 91

    campos[0] = "NFM"                                                 # 1 - Tipo de Registro
    campos[1] = str(dados.get("estabelecimento", ''))                 # 2 - Estabelecimento
    campos[2] = tipoOperacao(dados.get("ind_oper"))                   # 3 - Operação (E/S)
    campos[3] = modeloDoc(dados.get("cod_mod"))                       # 4 - Espécie (NF1, NFE, etc.)
    campos[4] = documentoProprio(dados.get("ind_emit"))               # 5 - Documento Próprio (S/N)
    campos[5] = ""                                                    # 6 - AIDF (Não disponível no SPED C100)
    campos[6] = str(dados.get("ser", ''))[:3]                         # 7 - Série
    campos[7] = ""                                                    # 8 - Subsérie (Não disponível no SPED C100)
    campos[8] = str(dados.get("num_doc", ''))                         # 9 - Número do Documento
    campos[9] = ""                                                    # 10 - Formulário Inicial
    campos[10] = ""                                                   # 11 - Formulário Final
    campos[11] = formatarData(dados.get("dt_doc"))                    # 12 - Data de Emissão
    campos[12] = situacaoDoc(dados.get("cod_sit"))                    # 13 - Situação do documento (Normal, Cancelado, etc.)
    campos[13] = formatarData(dados.get("dt_e_s"))                    # 14 - Data de Entrada/Saída
    campos[14] = str(dados.get("cod_part", ''))                       # 15 - Remetente/Destinatário
    campos[15] = "N"                                                  # 16 - GNRE Vinculada (Default 'N')
    campos[16] = ""                                                   # 17 - GNRE ICMS
    campos[17] = ""                                                   # 18 - GNRE Mês/Ano
    campos[18] = ""                                                   # 19 - GNRE Convênio
    campos[19] = ""                                                   # 20 - GNRE Data de Vencimento
    campos[20] = ""                                                   # 21 - GNRE Data de Recolhimento
    campos[21] = ""                                                   # 22 - GNRE Banco
    campos[22] = ""                                                   # 23 - GNRE Agência
    campos[23] = ""                                                   # 24 - GNRE Agência DV
    campos[24] = ""                                                   # 25 - GNRE Autenticado
    campos[25] = formatarValor(dados.get("vl_merc"))                  # 26 - Produtos
    campos[26] = formatarValor(dados.get("vl_frt"))                   # 27 - Frete
    campos[27] = formatarValor(dados.get("vl_seg"))                   # 28 - Seguro
    campos[28] = formatarValor(dados.get("vl_out_da"))                # 29 - Outras Despesas
    campos[29] = ""                                                   # 30 - ICMS Importação (Requer soma de C170 com CFOP '3xxx')
    campos[30] = ""                                                   # 31 - ICMS Importação Diferido
    campos[31] = formatarValor(dados.get("vl_ipi"))                   # 32 - IPI
    campos[32] = formatarValor(dados.get("vl_icms_st"))               # 33 - Substituição Retido
    campos[33] = formatarValor(dados.get("vl_serv_iss_total"))        # 34 - Serviços ISS (Vem da query agregada)
    campos[34] = formatarValor(dados.get("vl_desc"))                  # 35 - Desconto Total
    campos[35] = formatarValor(dados.get("vl_doc"))                   # 36 - Valor Total
    campos[36] = str(dados.get("qtd_itens", ''))                      # 37 - Quant. de Itens/Produtos
    campos[37] = 'S' if (dados.get("vl_icms_st", 0) or 0) > 0 and dados.get("ind_oper") == '0' else 'N' # 38 - Substituição Recolher
    campos[38] = "N"                                                  # 39 - Antecipado Recolher (Default 'N')
    campos[39] = "N"                                                  # 40 - Diferencial de Alíquotas (Default 'N')
    campos[40] = formatarValor(dados.get("vl_icms_st"))               # 41 - Vr. Contáb. Subst. Tributária
    campos[41] = formatarValor(dados.get("vl_bc_icms_st"))            # 42 - Base Cálc. Subst. Tributária
    campos[42] = ""                                                   # 43 - Vr. Contábil Antecipado
    campos[43] = ""                                                   # 44 - ISS Retido
    campos[44] = ""                                                   # 45 - Data de Retenção do ISS
    campos[45] = ""                                                   # 46 - Serviço
    campos[46] = ""                                                   # 47 - Data de Entrada no Estado
    campos[47] = tipoFrete(dados.get("ind_frt"))                      # 48 - Frete por Conta
    campos[48] = tipoFatura(str(dados.get("ind_pgto")))               # 49 - Fatura
    campos[49] = ""                                                   # 50 - Número do EEC
    campos[50] = ""                                                   # 51 - Número do Cupom
    campos[51] = ""                                                   # 52 - Receita Tributável COFINS
    campos[52] = ""                                                   # 53 - Receita Tributável PIS
    campos[53] = ""                                                   # 54 - Receita Tributável CSL 1
    campos[54] = ""                                                   # 55 - Receita Tributável CSL 2
    campos[55] = ""                                                   # 56 - Receita Tributável IRPJ 1
    campos[56] = ""                                                   # 57 - Receita Tributável IRPJ 2
    campos[57] = ""                                                   # 58 - Receita Tributável IRPJ 3
    campos[58] = ""                                                   # 59 - Receita Tributável IRPJ 4
    campos[59] = ""                                                   # 60 - COFINS Retido na Fonte
    campos[60] = ""                                                   # 61 - PIS Retido na Fonte
    campos[61] = ""                                                   # 62 - CSL Retido na Fonte
    campos[62] = ""                                                   # 63 - IRPJ Retido na Fonte
    campos[63] = "N"                                                  # 64 - Gera Transferência (Default 'N')
    campos[64] = ""                                                   # 65 - Observação
    campos[65] = ""                                                   # 66 - Alíquota da Substituição Tributária
    campos[66] = str(dados.get("chv_nfe", ''))                        # 67 - Chave Eletrônica
    campos[67] = ""                                                   # 68 - INSS Retido na Fonte
    campos[68] = ""                                                   # 69 - Base de Cálculo do COFINS/PIS não cumulativos
    campos[69] = ""                                                   # 70 - Motivo do Cancelamento
    campos[70] = ""                                                   # 71 - Natureza da Operação
    campos[71] = ""                                                   # 72 - Código da Informação Complementar
    campos[72] = ""                                                   # 73 - Complemento da Informação Complementar
    campos[73] = ""                                                   # 74 - Hora da Saída
    campos[74] = ""                                                   # 75 - UF de Embarque
    campos[75] = ""                                                   # 76 - Local de Embarque
    campos[76] = ""                                                   # 77 - Código Contábil
    campos[77] = ""                                                   # 78 - Chave NFE de Referência
    campos[78] = ""                                                   # 79 - Informação Adicional do Fisco
    campos[79] = "N"                                                  # 80 - Indicador de Operação com Consumidor Final (Default 'N')
    campos[80] = ""                                                   # 81 - Indicador de Presença do Comprador
    campos[81] = ""                                                   # 82 - Data da Contingência
    campos[82] = ""                                                   # 83 - Hora da Contingência
    campos[83] = ""                                                   # 84 - Reconhece NFe
    campos[84] = ""                                                   # 85 - NFe informada pelo contribuinte
    campos[85] = formatarValor(dados.get("vl_icms_deson_total"))      # 86 - Total do ICMS Desoneração (Vem da query agregada)
    campos[86] = ""                                                   # 87 - Prestador de Serviços em Obra de Construção Civil
    campos[87] = ""                                                   # 88 - CNO
    campos[88] = ""                                                   # 89 - Data de Escrituração
    campos[89] = formatarValor(dados.get("vl_fcp_st_total"))          # 90 - Total do FCP Substituição (Vem da query agregada)
    campos[90] = "N"                                                  # 91 - NF-e Saída de Terceiros (Default 'N')

    return "|".join(campos) + "|"