from src.config.db.base import Base

from sqlalchemy import Column, Integer, String, DECIMAL, Boolean, ForeignKey
from sqlalchemy.orm import relationship

class RegistroC170(Base):
    __tablename__ = "registro_c170"

    id = Column(Integer, primary_key=True, autoincrement=True)
    empresa_id = Column(Integer, ForeignKey("empresas.id"), index=True)
    c100_id = Column(Integer, ForeignKey("c100.id"), index=True)

    periodo = Column(String(10))
    reg = Column(String(10))
    num_item = Column(String(10))
    cod_item = Column(String(60))
    descr_compl = Column(String(255))
    qtd = Column(DECIMAL(15, 4))
    unid = Column(String(10))
    vl_item = Column(DECIMAL(15, 2))
    vl_desc = Column(DECIMAL(15, 2))
    ind_mov = Column(String(5))
    cst_icms = Column(String(10))
    cfop = Column(String(10))
    cod_nat = Column(String(11))
    vl_bc_icms = Column(DECIMAL(15, 2))
    aliq_icms = Column(DECIMAL(5, 2))
    vl_icms = Column(DECIMAL(15, 2))
    vl_bc_icms_st = Column(DECIMAL(15, 2))
    aliq_st = Column(DECIMAL(5, 2))
    vl_icms_st = Column(DECIMAL(15, 2))
    ind_apur = Column(String(5))
    cst_ipi = Column(String(10))
    cod_enq = Column(String(10))
    vl_bc_ipi = Column(DECIMAL(15, 2))
    aliq_ipi = Column(DECIMAL(5, 2))
    vl_ipi = Column(DECIMAL(15, 2))
    cst_pis = Column(String(10))
    vl_bc_pis = Column(DECIMAL(15, 2))
    aliq_pis = Column(DECIMAL(5, 2))
    quant_bc_pis = Column(DECIMAL(15, 4))
    aliq_pis_reais = Column(DECIMAL(15, 4))
    vl_pis = Column(DECIMAL(15, 2))
    cst_cofins = Column(String(10))
    vl_bc_cofins = Column(DECIMAL(15, 2))
    aliq_cofins = Column(DECIMAL(5, 2))
    quant_bc_cofins = Column(DECIMAL(15, 4))
    aliq_cofins_reais = Column(DECIMAL(15, 4))
    vl_cofins = Column(DECIMAL(15, 2))
    cod_cta = Column(String(255))
    vl_abat_nt = Column(DECIMAL(15, 2))
    filial = Column(String(10))
    ind_oper = Column(String(5))
    cod_part = Column(String(60))
    num_doc = Column(String(20))
    chv_nfe = Column(String(60))
    ncm = Column(String(44), default="")
    mercado = Column(String(15), default="")
    aliquota = Column(String(10), default="")
    resultado = Column(String(20))
    ativo = Column(Boolean, default=True)

    c100 = relationship("RegistroC100", back_populates="itens")
